COL_EVENT = 'event'
COL_GENERATION = 'gen'
COL_TIME = 'time'
COL_FITNESS = 'fitness'

OUTPUT_LABELS = [
    COL_EVENT,
    COL_GENERATION,
    COL_TIME,
    COL_FITNESS,
]

EVENT_BEST_IN_GEN = 'bestingen'
EVENT_NEW_BEST = 'newbest'
EVENT_DIVERSITY = 'diversity'

OUTPUT_EVENTS = [
    EVENT_BEST_IN_GEN,
    EVENT_NEW_BEST,
    EVENT_DIVERSITY,
]

